# Generated by Django 4.2.3 on 2023-07-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnos',
            old_name='recordatorio',
            new_name='recordatorios',
        ),
    ]
