# Generated by Django 4.2.3 on 2023-07-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_recordatorio_turnos_recordatorios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
