# Generated by Django 4.2.3 on 2023-07-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_turnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='profesion',
        ),
    ]
